import { useEffect, useId, useState } from 'react'

let mermaidPromise

function loadMermaid() {
  if (!mermaidPromise) {
    mermaidPromise = import('mermaid').then(({ default: mermaid }) => {
      mermaid.initialize({
        startOnLoad: false,
        theme: 'base',
        fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
        themeVariables: {
          darkMode: true,
          background: '#10161d',
          primaryColor: '#1c1533',
          primaryTextColor: '#e7edf3',
          primaryBorderColor: '#a78bfa',
          secondaryColor: '#161d26',
          secondaryBorderColor: '#232c37',
          tertiaryColor: '#161d26',
          tertiaryBorderColor: '#232c37',
          lineColor: '#8b98a6',
          textColor: '#e7edf3',
          mainBkg: '#1c1533',
          nodeBorder: '#a78bfa',
          clusterBkg: '#161d26',
          clusterBorder: '#232c37',
          edgeLabelBackground: '#10161d',
          actorBkg: '#1c1533',
          actorBorder: '#a78bfa',
          actorTextColor: '#e7edf3',
          signalColor: '#8b98a6',
          signalTextColor: '#e7edf3',
          labelBoxBkgColor: '#1c1533',
          labelBoxBorderColor: '#a78bfa',
          labelTextColor: '#e7edf3',
          gitBranchLabel0: '#e7edf3',
          git0: '#a78bfa',
          git1: '#e879f9',
          git2: '#34d399',
          git3: '#22d3ee',
        },
      })
      return mermaid
    })
  }
  return mermaidPromise
}

export default function Mermaid({ chart }) {
  const rawId = useId().replace(/:/g, '')
  const [svg, setSvg] = useState(null)
  const [error, setError] = useState(null)

  useEffect(() => {
    let cancelled = false

    loadMermaid()
      .then((mermaid) => mermaid.render(`mermaid-${rawId}`, chart))
      .then(({ svg: rendered }) => {
        if (!cancelled) setSvg(rendered)
      })
      .catch((err) => {
        if (!cancelled) setError(err instanceof Error ? err.message : String(err))
      })

    return () => {
      cancelled = true
    }
  }, [chart, rawId])

  if (error) {
    return (
      <div className="not-prose my-6 rounded-lg border border-red-500/30 bg-red-500/10 p-4 font-mono text-sm text-red-300">
        Mermaid diagram error: {error}
      </div>
    )
  }

  if (!svg) {
    return (
      <div className="not-prose my-6 flex h-32 items-center justify-center rounded-lg border border-border bg-surface text-sm text-muted">
        Rendering diagram…
      </div>
    )
  }

  return (
    // svg is generated by mermaid from our own post content, not untrusted input
    <div
      className="not-prose my-6 overflow-x-auto rounded-lg border border-border bg-surface p-6 [&_svg]:mx-auto"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  )
}
